name: text-regex-replace
version: '0.1.1.4'
synopsis: Easy replacement when using text-icu regexes.
description: ! 'This provides a convenient API for doing replacements off of a regular

  expression, similar to what regex libraries in other languages provide.


  At this point, this hasn''t been used enough to have any idea of its

  performance. Caveat emptor.'
category: Data, Text
author: Eric Rochester
maintainer: erochest@gmail.com
license: Apache-2.0
git: git://github.com/erochest/text-regex-replace.git
dependencies:
- text >=1.2
- text-icu >=0.7 && <0.9
library:
  source-dirs: src
  exposed-modules:
  - Data.Text.ICU.Replace
  dependencies:
  - base >=4.7 && <5
  - attoparsec >=0.12 && <0.15
tests:
  text-regex-replace-specs:
    main: Specs.hs
    source-dirs: specs
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - base
    - text-regex-replace
    - QuickCheck
    - smallcheck
    - hspec
